spring:
  profiles:
    active: prod



  servlet:

    multipart:
      max-file-size: 20MB
      max-request-size: 20MB



wxapi:
  code2Session: https://api.weixin.qq.com/sns/jscode2session?appid=
  appid: wx969d9a910a1d1103
  appSecret: 7bc089f70c22c99391fefc0d2a397eaf
  get_accesstoken: https://api.weixin.qq.com/cgi-bin/token?grant_type=
  mch_id:
  TRADETYPE:
  key:
  pay_url: https://api.mch.weixin.qq.com/pay/unifiedorder
  notify_url: JSAPI

jwt:
  secretKey: lengend
  effectiveTime: 10800



server:
  port: 83

