spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password: lengend-redis
    timeout: 500ms
    jedis:
      pool:
        max-idle: 8
        min-idle: 2
        max-active: 8
        max-wait: 10000ms

  datasource:
    hikari:
      connection-init-sql: SET NAMES utf8mb4

    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1/miniapp?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lengend
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 200   #PreparedStatement缓存大小
      filters: stat,wall          #stat:web监控   wall：sql防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      test-while-idle: true  #申请连接的时候检测，如果空闲时间大


file:
  webImgUrl: https://api.zblade.top/jobhunter/headimg/
  webFileUrl: https:/api.zblade.top/jobhunter/files/
  webLogoUrl: https://api.zblade.top/jobhunter/logo/
  webFeedUrl: https://api.zblade.top/jobhunter/feedback/
  imgUrl: /usr/local/jobhunter/headimg/
  fileUrl: /usr/local/jobhunter/files/
  defaultImgUrl: /Unicorn.png
  logo_url: /usr/local/jobhunter/logo/
  defaultLogo: /Unicorn.png
  feedUrl: /usr/local/jobhunter/feedback/

