spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 500ms

    jedis:
      pool:
        max-idle: 8
        min-idle: 2
        max-active: 8
        max-wait: 10000ms


wxapi:
  code2Session:
  appid:
  appSecret:
  get_accesstoken:
  mch_id:
  TRADETYPE:
  key:
  pay_url: https://api.mch.weixin.qq.com/pay/unifiedorder
  notify_url: JSAPI

file:
  imgUrl: E:/
  fileUrl: E:/
server:
  port: 83

